import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import Header from "~/components/general/Header";
import Providers from "./provider";

export const metadata: Metadata = {
  title: "Lizzy Boat",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <Providers>
          <Header />
          <main className="min-h-[calc(100vh_-_65px)]">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
